### ISSUE TITLE
Demo isn't working, state change not causing a re-render

### ISSUE THREAD

**Issue by jaydanurwin** [adobe/lit-mobx#112]
### Expected Behaviour

After a lot of troubleshooting and attempting to use this package in my own project I couldn't seem to get the component to re-render when the store values are updated. I decided to go back to basics and try the demo code in the README to see if I was missing something simple but I can't even seem to get the sample to work. 😞 Am I missing something here? 

### Actual Behaviour

The component is mounting but it isn't updating state at all when the increment function is called

### Reproduce Scenario

I created a [stackblitz](https://stackblitz.com/edit/vite-9tqgru?file=my-element.ts) with a reproducible example

**Comment by benjamind** [comment]
Interesting, this looks right at first glance, perhaps something broke in usage with the recent lit 2 rc release. Thanks for bringing this to our attention!

**Comment by jaydanurwin** [comment]
I'm just happy to hear I'm not crazy haha 😅  I found this package yesterday and spent the better half of 3 hours trying to figure it out with my own code before I finally just tried the demo code. Thanks for looking into it!

**Comment by benjamind** [comment]
Ah, you're using mobx 6, and I think the demo is only written for mobx 5.

It does however work with mobx 6:

https://stackblitz.com/edit/vite-twrhjq?file=my-element.ts

**Comment by jaydanurwin** [comment]
Awesome, thank you for the quick reply on this and the example link! I am brand new to Mobx but so far it seems like it's going to be a perfect fit for my project using Lit. 

Side note: I might even do a YouTube tutorial on this package because it's one of the best state management solutions I've found for Lit.

**Comment by benjamind** [comment]
Sounds good! Mobx and lit do work pretty well together indeed. I will close this ticket out, and maybe file an issue later to rework our demos for both v5 and v6 at some point.

**Comment by kobleistvan** [comment]
Thankyou!! 
Kind reminder to update the demo for mobx 6

**Comment by spencercap** [comment]
it seems the magic needed is `makeObservable` in the constructor for mobx 6 to work. 

```ts
// create a mobx observable
class Counter {
	@observable
	public count = 0;

	@action
	public increment() {
		this.count++;
	}

	public constructor() {
		makeObservable(this); // has to have this!
	}
}
```

this is how to get the decorator syntax working
