### ISSUE TITLE
Upgrade to Lit 3

### ISSUE THREAD

**Issue by cristianmadularu** [adobe/lit-mobx#167]
With the release of Lit 3, coud we please also update the mobx lib in order to use it?

<img width="240" alt="image" src="https://github.com/adobe/lit-mobx/assets/124408005/bed19a99-7868-4bad-8f2a-751656c95813">

Thank you

**Comment by Westbrook** [comment]
Definitely something we'd like to support at some point! Thanks for getting this issue posted.

We'd be happy to accept a PR to modify this to `^2.0.0 || ^3.0.0`, but it may be a little while before we're able to go to this on our end.

**Comment by cristianmadularu** [comment]
Thank you @Westbrook 

Would this do it?
https://github.com/adobe/lit-mobx/pull/168

**Comment by cristianmadularu** [comment]
Any update on this? Thank you! Please note that I have created a PR for it.

**Comment by RoXuS** [comment]
+1

**Comment by benjamind** [comment]
I'll try and take a look at this soon and get a new version published, am unfortunately laid low with the virus we're all ignoring and I believe @Westbrook is away on vacation.

**Comment by cristianmadularu** [comment]
Thank you

**Comment by benjamind** [comment]
This should now be fixed in the v2.2.1 release

**Comment by cristianmadularu** [comment]
Yup, I just upgraded and it looks good. Thank you @benjamind

**Comment by benjamind** [comment]
Thanks for the prompt!
