### ISSUE TITLE
No tests were run as of today

### ISSUE THREAD

**Issue by motss** [adobe/lit-mobx#20]
## Description

@benjamind @Westbrook 

It's surprising to see  no tests were run in CircleCI even though #7 and #8 were added to resolve the testing portion.

As you can see this line does not actually run any of the tests after the build step https://github.com/adobe/lit-mobx/blob/682b7a61dd9f7cc787e1216d63f383b93b4e93ce/.circleci/config.yml#L30

**Comment by benjamind** [comment]
Thanks for bringing this to our attention. Will get on it asap.
