### ISSUE TITLE
Add release tags to make it easier to see changes between releases

### ISSUE THREAD

**Issue by pureooze** [adobe/lit-mobx#33]
Would it be possible to add release tags on this github repo? It would make it a lot easier to see a diff of what has been changed between releases. At the moment is can be a bit confusing trying to figure out what was added in a new release.

I believe adding releases also allows dependabot to provide a changelog for updates, which is also nice 😃

**Comment by benjamind** [comment]
Good idea, will try and find some time to get this done.

**Comment by benjamind** [comment]
Closing as we now have release tags for new versions and a changelog being generated.

**Comment by pureooze** [comment]
Awesome, thanks a lot for getting this in!
