### ISSUE TITLE
Does not work with MobX 6.0.0+

### ISSUE THREAD

**Issue by ForestKatsch** [adobe/lit-mobx#69]
While the `package.json` does require MobX `^5.0.0`, I installed `@adobe/lit-mobx` after `mobx` and was wondering why nothing was working.

(Reproduction: https://stackblitz.com/edit/lit-mobx-typescript-sfzprc?file=package.json and replace `^5.15.4` with `^6.0.0`; the button no longer works.)

**Comment by Westbrook** [comment]
This super interesting in that when I first open your reproduction link, it works! Currently, it loads as ^6.0.0, a la: https://stackblitz.com/edit/lit-mobx-typescript-taiiqm?file=package.json

When I futz with the version strings, it fails. 😱 

I wonder if something happens in the package lock where once it's had a ^5.0.0 versions it keeps it internal to `@adobe/lit-mobx`, even if you update the project to have ^6.0.0.

@benjamind can you think of any changes in 6.0.0 in specific that might cause issues? Should we see about getting two test processes going, one with ^5.0.0 and one with ^6.0.0 to ensure a smooth transition here?

**Comment by milesje** [comment]
I was just getting ready to upgrade Mobx to version 6. Glad I did a little research before I did. I will wait to see the outcome of this issue. I may have to run a test to see what happens if I do upgrade it it take too long.

**Comment by ErikGrimes** [comment]
@Westbrook 

I upgraded lit-mobx over the weekend to mobx 6 and used it in a fairly large project.  I haven't run across issues.

**Comment by benjamind** [comment]
I can't think of anything specifically that should cause issues in 6, as far as I understand it nothing we depend on changed here.

I agree though we should probably get a test suite running in 5 and 6 to confirm.

**Comment by peter-mogensen** [comment]
Totally clueless backend developer here... but...
The changelog for Mobx 6, says under "breaking changes":
_"The `decorate` API has been removed, and needs to be replaced by `makeObservable` in the constructor of the targeted class. It accepts the same arguments. The `mobx-undecorate` can transform this automatically."_

I see a lot of the examples using decorate, so breakage would seem expected.

**Comment by benjamind** [comment]
It would.indeed break the examples. But not the integration. Will try and work up some examples of usage under 6 soon, but it should be fairly similar to usage of any observable property under mobx 6.

**Comment by benjamind** [comment]
Have confirmed current build is working with Mobx v6 - https://stackblitz.com/edit/lit-mobx-typescript-mobx6?file=index.ts
