### ISSUE TITLE
Lit-Mobx and partial rerendering

### ISSUE THREAD

**Issue by lolive** [adobe/lit-mobx#74]
Hi everyone.
That's not a bug report.
But more a question.
[May be StackOverflow is better suited for that.
I will elaborate there, if needed.]
My question is about partial rerendering.
For example when a component's render() function
iterates over an observable array to build (let's say) &lt;tr&gt;
of a table.
What if I push a new item inside that array? Or splice a new item?
Will the whole table be rerendered?
Or will only one &lt;tr&gt; element be created and inserted 
at the correct location in the existing table?

Thanks for your help.

PS: a similar question is when you sort the array.
Is there a way for &lt;tr&gt; to mimic that sort in the UI without rerendering?

**Comment by lolive** [comment]
After re-reading the lit-html documentation for <a href="https://lit-html.polymer-project.org/guide/writing-templates#repeating-templates-with-the-repeat-directive">repeat</a>, I now wonder if simply using ${repeat ...} upon the arrays mentionned above will manage my use cases natively.
[Naively, I would say yes]

**Comment by benjamind** [comment]
This is more a `lit-element`/`lit-html` question than a `lit-mobx` one.

`lit-mobx` will ensure that the `lit-element` render function is triggered whenever any observable property or object that is in the render function is updated. How lit-html will update the DOM when that render function is called is a question best posed to the lit team. I'd suggest joining the [Slack](https://lit-element.polymer-project.org/guide/community) to get best response.
