### ISSUE TITLE
Batch updates and lit-mobx

### ISSUE THREAD

**Issue by lolive** [adobe/lit-mobx#82]
I just read an article:
https://dev.to/open-wc/litelement-a-deepdive-into-batched-updates-3hh
that details how LitElement avoids multiple calls to requestUpdate() for any given block of code.

Thanks to that clever trick, a block of code that updates several observables of the litElement will only trigger
the requestUpdate() once.

Does lit-mobx implement something similar? So when a block of code updates several values of my store data, that should all trigger a requestUpdate(), only one requestUpdate() will be launched (as explained in the article).

**Comment by benjamind** [comment]
Yes it uses the same mechanism calling [requestUpdate()](https://github.com/adobe/lit-mobx/blob/trunk/src/lib/mixin.ts#L39) on observable change, `lit-element` in turn guards against duplicate execution of the update cycle [here](https://github.com/Polymer/lit-element/blob/master/src/lib/updating-element.ts#L689) only requesting an update once per tick.
