### ISSUE TITLE
Lit 2 version

### ISSUE THREAD

**Issue by Artur-** [adobe/lit-mobx#85]
Please create a version 2.0.0(.pre1?) that uses Lit 2 (currently `2.0.0.pre1`)

**Comment by benjamind** [comment]
Reopening as this is not yet fixed, we haven't published the `2.0.0` release. We are in the process of preparing a `2.0.0-rc` release while we await the official lit 2.0.0 release, but are working through some github action issues...

**Comment by benjamind** [comment]
Version `2.0.0-rc.4` is now published....we'll publish an official `2.0.0` when lit does.

**Comment by jaydanurwin** [comment]
Any updates on this now that Lit 2 has been officially released? I'm super thankful for this package and I'd love to see it officially support the newest version of Lit.

**Comment by benjamind** [comment]
Good call, I'll release the official 2.0.0 version today!

**Comment by benjamind** [comment]
`v2.0.0` has now been published.
